name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        default: "minor"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.31
        with:
          version-minor: ${{ inputs.environment == 'minor' && 'true' }}
          version-major: ${{ inputs.environment == 'major' && 'true' }}
